-- CreateTable
CREATE TABLE "Categories" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "updatedAt" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "createdAt" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "tourId" INTEGER NOT NULL,
    CONSTRAINT "Categories_tourId_fkey" FOREIGN KEY ("tourId") REFERENCES "Tours" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
